### ISSUE TITLE
[Feature Request] 支持任意status code以转发API

### ISSUE THREAD

**Issue by diauweb** [ChenYFan/ClientWorker#11]
很多 API 在返回时都会使用状态码标识返回结果，因此可能会出现多种非“正常”但有效的状态码。目前 ClientWorker 在遇到非 200 或手动设置的状态码时会失败，而预期应将“合理”失败的结果（4xx）正确返回给前端。

**Comment by ChenYFan** [comment]
并发的时候可能会有部分请求失败，如果扩大请求状态，可能会出现有一些并发成功时总请求失败的问题。

当然，如果有必要，我会让此配置项成为正则

**Comment by diauweb** [comment]
> 并发的时候可能会有部分请求失败，如果扩大请求状态，可能会出现有一些并发成功时总请求失败的问题。
> 
> 当然，如果有必要，我会让此配置项成为正则

因 API 请求的特殊性，在访问 API 时应采用单源单请求模式以获得正确结果。所以并发在这个 scenario 里面不是问题。如果可以，可以考虑添加新的顺序发起请求的引擎。

**Comment by ChenYFan** [comment]
ClienWorker 3.0.0-beta-2发布，cdnjs可用https://lib.baomitu.com/clientworker/3.0.0-beta-2/dist/cw.js
