### ISSUE TITLE
怎么卸载

### ISSUE THREAD

**Issue by xiaokuqwq** [ChenYFan/ClientWorker#12]

**Comment by ChenYFan** [comment]
和普通sw卸载方式一样：
1.不要删除cw.js
2.将安装代码替换为卸载代码

**Comment by 1834423612** [comment]
请问卸载代码是啥？现在在我网站里面关不掉了，安装也安不上，关也关不掉 :(

**Comment by ChenYFan** [comment]
> 请问卸载代码是啥？现在在我网站里面关不掉了，安装也安不上，关也关不掉 :(

...这东西不应该在本地测试好在上生产吗...

移除cw和移除sw一样，**请不要直接删掉cw.js和安装代码**，如果已删除请将原文件复原，并将安装代码改成：


```
navigator.serviceWorker.getRegistrations().then(function(registrations) {
 for(let registration of registrations) {
  registration.unregister()
} })
```


在足够长的一段时间后才能移除js文件，否则很有可能有一部分访客没能获得卸载代码导致无法卸载也无法更新。

**Comment by 1834423612** [comment]
> > 请问卸载代码是啥？现在在我网站里面关不掉了，安装也安不上，关也关不掉 :(
> 
> ...这东西不应该在本地测试好在上生产吗...
> 
> 移除cw和移除sw一样，**请不要直接删掉cw.js和安装代码**，如果已删除请将原文件复原，并将安装代码改成：
> 
> ```
> navigator.serviceWorker.getRegistrations().then(function(registrations) {
>  for(let registration of registrations) {
>   registration.unregister()
> } })
> ```
> 
> 在足够长的一段时间后才能移除js文件，否则很有可能有一部分访客没能获得卸载代码导致无法卸载也无法更新。

好的，谢谢😃
