### ISSUE TITLE
ICP绕备、家宽、动态加速，求助

### ISSUE THREAD

**Issue by zxmacc** [ChenYFan/ClientWorker#5]
大佬，我使用了文档中的三文件全域安装，部署在vercel上，[cw-test-nu.vercel.app](https://cw-test-nu.vercel.app/)
源站地址为1.117.73.17。

然后是直接使用了，您提到的ICP绕备、家宽、动态加速这个例子。配置文件除了ip地址变了，应该和文档中的没有区别
然后也给源站开了ssl，用的zerossl，和你在v2ex上提到的应该是同一家
然后我也加上了Access-Control-Allow-Origin和Access-Control-Allow-Credentials为true
Access-Control-Allow-Origin允许的是cw-test-nu.vercel.app
使用的是宝塔面板部署的

但不知道为什么，cw一直会重试安装好像，然后我也试过关闭nginx防火墙，似乎也没什么用
因为没什么基础，也不清楚是哪里有问题
以下有三张截图：
![image](https://user-images.githubusercontent.com/71143103/179961831-066bdfcf-8d83-4117-b291-a8853381ee9e.png)
![image](https://user-images.githubusercontent.com/71143103/179961931-7354571d-8b5e-4268-9e27-7b43da581a1f.png)

![G{@5RLODQV8NV%DIS2_R$XT](https://user-images.githubusercontent.com/71143103/179961141-92d282ea-231d-4ac9-b2ba-0530a43793d7.png)

**Comment by zxmacc** [comment]
第一个preflight: true，截图中的，我给改掉了，现在和文档中一样是preflight: false

**Comment by zxmacc** [comment]
这个是链接着vercel的仓库https://github.com/zxmacc/cw-test

**Comment by zxmacc** [comment]
我看到隔壁的pulls有个变更，去除多余的timeout，跟着去除了一下，似乎还是不行QWQ

**Comment by ChenYFan** [comment]
![image](https://user-images.githubusercontent.com/53730587/180102658-e004022a-3e23-4330-b180-165829edc9f8.png)

ACAO头应该配置为`https://cw-test-nu.vercel.app`

**Comment by ChenYFan** [comment]
为了方便测试，我建议干脆直接设置为`*`，成功后再改回

**Comment by ChenYFan** [comment]
插一句，如果纯静态的话上传到文件存储会快的多

**Comment by zxmacc** [comment]
> 插一句，如果纯静态的话上传到文件存储会快的多

好的，谢谢大佬，已解决~
